name: CI-CD
on: [push, pull_request]

jobs:
  job1:
    name: TDD tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Set up JDK Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Maven verify
        run: mvn clean verify

      - name: Maven Test
        run: mvn test -DDISCORD_WEBHOOK_URL=url